FROM jenkins/jenkins:lts

USER root

RUN apt-get update \
    && apt-get install -y curl

RUN curl -fsSL https://get.docker.com | sh

RUN usermod -aG docker jenkins

RUN curl --http1.1 -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose \
    && chmod +x /usr/local/bin/docker-compose


USER jenkins