

services:
  #mongo:
    #image: mongo:7.0
    #command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    #container_name: shopimax-dbv2
    #restart: always
    #ports:
    #  - '27017:27017'
    #volumes:
    #  - shopimax-dbv2-data:/data/db
    #networks:
    #  - shopimax-network
    #healthcheck:
      #test: ["CMD", "mongosh", "--host", "127.0.0.1", "--eval", "db.runCommand('ping').ok"]
      #interval: 10s
      #timeout: 5s
      #retries: 5

  shopimax-apiv2:
    build:
      context: .
    #container_name: shopimax-apiv2
    restart: on-failure
    ports:
      - '3003:3002'
    #depends_on:
    #  - mongo
    networks:
      - shopimax-network
    environment:
      - PORT=${PORT}
    volumes:
      - .:/app
      - /app/node_modules

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: shopimax-jenkins-${BUILD_ID}
    restart: always
    privileged: true
    user: root
    ports:
      - '8080'
      # - '50000:50000'
    networks:
      - shopimax-network
    environment:
      - BUILD_ID=${BUILD_ID}
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  shopimax-dbv2-data:
  jenkins_home:

networks:
  shopimax-network:
    driver: bridge
